# Generated by Django 4.2.30 on 2026-06-28 08:13

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(default=uuid.uuid4, max_length=50, unique=True),
                ),
                ("invoice_num", models.CharField(default="Invoice", max_length=100)),
                (
                    "invoice_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("customer_email", models.EmailField(max_length=254)),
                ("items", models.JSONField(default=list)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("gst_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "gst_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "cgst",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "sgst",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "igst",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "upi_id",
                    models.CharField(
                        blank=True, default="voxlomtmb@tmb", max_length=100, null=True
                    ),
                ),
                ("status", models.CharField(default="pending", max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "billing_company",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("billing_address", models.TextField(blank=True, null=True)),
                (
                    "billing_city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "billing_state",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("billing_pin", models.CharField(blank=True, max_length=20, null=True)),
                ("billing_gst", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "billing_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "payment_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "ccavenue_tracking_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "ccavenue_payment_mode",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
    ]
